"""database_init

Revision ID: 8a2cee70598a
Revises: 
Create Date: 2026-05-15 19:48:54.641885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a2cee70598a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=30), nullable=False),
    sa.Column('product_name', sa.String(length=150), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('principal_name', sa.String(length=100), nullable=False),
    sa.Column('target_industry', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('dim_region',
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('region_code', sa.String(length=20), nullable=False),
    sa.Column('region_name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_domestic', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('region_id'),
    sa.UniqueConstraint('region_code')
    )
    op.create_table('dim_segment',
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('segment_code', sa.String(length=20), nullable=False),
    sa.Column('segment_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('segment_id'),
    sa.UniqueConstraint('segment_code')
    )
    op.create_table('dim_time',
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('full_date', sa.Date(), nullable=False),
    sa.Column('day_of_week', sa.String(length=20), nullable=False),
    sa.Column('month_name', sa.String(length=20), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('time_id')
    )
    op.create_index(op.f('ix_dim_time_full_date'), 'dim_time', ['full_date'], unique=True)
    op.create_index(op.f('ix_dim_time_year'), 'dim_time', ['year'], unique=False)
    op.create_table('dim_customer',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=30), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=False),
    sa.Column('customer_type', sa.String(length=50), nullable=False),
    sa.Column('industry_segment', sa.String(length=100), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['dim_region.region_id'], ),
    sa.PrimaryKeyConstraint('customer_id'),
    sa.UniqueConstraint('customer_code')
    )
    op.create_index(op.f('ix_dim_customer_region_id'), 'dim_customer', ['region_id'], unique=False)
    op.create_table('dim_employee',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('employee_code', sa.String(length=30), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['dim_region.region_id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['dim_segment.segment_id'], ),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('employee_code')
    )
    op.create_index(op.f('ix_dim_employee_region_id'), 'dim_employee', ['region_id'], unique=False)
    op.create_index(op.f('ix_dim_employee_segment_id'), 'dim_employee', ['segment_id'], unique=False)
    op.create_table('dim_plant',
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('plant_code', sa.String(length=30), nullable=False),
    sa.Column('plant_name', sa.String(length=150), nullable=False),
    sa.Column('plant_type', sa.String(length=50), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['dim_region.region_id'], ),
    sa.PrimaryKeyConstraint('plant_id'),
    sa.UniqueConstraint('plant_code')
    )
    op.create_index(op.f('ix_dim_plant_region_id'), 'dim_plant', ['region_id'], unique=False)
    op.create_table('dim_warehouse',
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_code', sa.String(length=30), nullable=False),
    sa.Column('warehouse_name', sa.String(length=150), nullable=False),
    sa.Column('warehouse_type', sa.String(length=50), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['dim_region.region_id'], ),
    sa.PrimaryKeyConstraint('warehouse_id'),
    sa.UniqueConstraint('warehouse_code')
    )
    op.create_index(op.f('ix_dim_warehouse_region_id'), 'dim_warehouse', ['region_id'], unique=False)
    op.create_table('fact_inventory',
    sa.Column('inventory_fact_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('opening_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closing_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('inventory_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['dim_product.product_id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['dim_segment.segment_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['dim_warehouse.warehouse_id'], ),
    sa.PrimaryKeyConstraint('inventory_fact_id')
    )
    op.create_index(op.f('ix_fact_inventory_product_id'), 'fact_inventory', ['product_id'], unique=False)
    op.create_index(op.f('ix_fact_inventory_segment_id'), 'fact_inventory', ['segment_id'], unique=False)
    op.create_index(op.f('ix_fact_inventory_time_id'), 'fact_inventory', ['time_id'], unique=False)
    op.create_index(op.f('ix_fact_inventory_warehouse_id'), 'fact_inventory', ['warehouse_id'], unique=False)
    op.create_table('fact_production',
    sa.Column('production_fact_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('planned_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('yield_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('total_production_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['dim_plant.plant_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['dim_product.product_id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['dim_segment.segment_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['dim_time.time_id'], ),
    sa.PrimaryKeyConstraint('production_fact_id')
    )
    op.create_index(op.f('ix_fact_production_plant_id'), 'fact_production', ['plant_id'], unique=False)
    op.create_index(op.f('ix_fact_production_product_id'), 'fact_production', ['product_id'], unique=False)
    op.create_index(op.f('ix_fact_production_segment_id'), 'fact_production', ['segment_id'], unique=False)
    op.create_index(op.f('ix_fact_production_time_id'), 'fact_production', ['time_id'], unique=False)
    op.create_table('fact_sales',
    sa.Column('sales_fact_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('quantity_ordered', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_margin_pct', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.customer_id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['dim_employee.employee_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['dim_product.product_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['dim_region.region_id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['dim_segment.segment_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['dim_warehouse.warehouse_id'], ),
    sa.PrimaryKeyConstraint('sales_fact_id')
    )
    op.create_index(op.f('ix_fact_sales_customer_id'), 'fact_sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_employee_id'), 'fact_sales', ['employee_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_product_id'), 'fact_sales', ['product_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_region_id'), 'fact_sales', ['region_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_segment_id'), 'fact_sales', ['segment_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_time_id'), 'fact_sales', ['time_id'], unique=False)
    op.create_index(op.f('ix_fact_sales_warehouse_id'), 'fact_sales', ['warehouse_id'], unique=False)
    op.create_table('fact_shipment',
    sa.Column('shipment_fact_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.Column('shipping_method', sa.String(length=50), nullable=False),
    sa.Column('freight_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('on_time_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['dim_customer.customer_id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['dim_region.region_id'], ),
    sa.ForeignKeyConstraint(['time_id'], ['dim_time.time_id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['dim_warehouse.warehouse_id'], ),
    sa.PrimaryKeyConstraint('shipment_fact_id')
    )
    op.create_index(op.f('ix_fact_shipment_customer_id'), 'fact_shipment', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fact_shipment_region_id'), 'fact_shipment', ['region_id'], unique=False)
    op.create_index(op.f('ix_fact_shipment_time_id'), 'fact_shipment', ['time_id'], unique=False)
    op.create_index(op.f('ix_fact_shipment_warehouse_id'), 'fact_shipment', ['warehouse_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fact_shipment_warehouse_id'), table_name='fact_shipment')
    op.drop_index(op.f('ix_fact_shipment_time_id'), table_name='fact_shipment')
    op.drop_index(op.f('ix_fact_shipment_region_id'), table_name='fact_shipment')
    op.drop_index(op.f('ix_fact_shipment_customer_id'), table_name='fact_shipment')
    op.drop_table('fact_shipment')
    op.drop_index(op.f('ix_fact_sales_warehouse_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_time_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_segment_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_region_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_product_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_employee_id'), table_name='fact_sales')
    op.drop_index(op.f('ix_fact_sales_customer_id'), table_name='fact_sales')
    op.drop_table('fact_sales')
    op.drop_index(op.f('ix_fact_production_time_id'), table_name='fact_production')
    op.drop_index(op.f('ix_fact_production_segment_id'), table_name='fact_production')
    op.drop_index(op.f('ix_fact_production_product_id'), table_name='fact_production')
    op.drop_index(op.f('ix_fact_production_plant_id'), table_name='fact_production')
    op.drop_table('fact_production')
    op.drop_index(op.f('ix_fact_inventory_warehouse_id'), table_name='fact_inventory')
    op.drop_index(op.f('ix_fact_inventory_time_id'), table_name='fact_inventory')
    op.drop_index(op.f('ix_fact_inventory_segment_id'), table_name='fact_inventory')
    op.drop_index(op.f('ix_fact_inventory_product_id'), table_name='fact_inventory')
    op.drop_table('fact_inventory')
    op.drop_index(op.f('ix_dim_warehouse_region_id'), table_name='dim_warehouse')
    op.drop_table('dim_warehouse')
    op.drop_index(op.f('ix_dim_plant_region_id'), table_name='dim_plant')
    op.drop_table('dim_plant')
    op.drop_index(op.f('ix_dim_employee_segment_id'), table_name='dim_employee')
    op.drop_index(op.f('ix_dim_employee_region_id'), table_name='dim_employee')
    op.drop_table('dim_employee')
    op.drop_index(op.f('ix_dim_customer_region_id'), table_name='dim_customer')
    op.drop_table('dim_customer')
    op.drop_index(op.f('ix_dim_time_year'), table_name='dim_time')
    op.drop_index(op.f('ix_dim_time_full_date'), table_name='dim_time')
    op.drop_table('dim_time')
    op.drop_table('dim_segment')
    op.drop_table('dim_region')
    op.drop_table('dim_product')
    # ### end Alembic commands ###
